version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./app:/app
  redis:
    image: redis:alpine
    restart: always
